worker:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 80
  configOptions: "-Dspark.scheduler.mode=FAIR" 
  resources:
    requests:
      cpu: 500m
      memory: "1Gi"
    limits:
      cpu: 1
      memory: "2Gi"
  extraContainerPorts: 
    - name: stream-process
      containerPort: 8181
      protocol: TCP

master:
  configOptions: "-Dspark.scheduler.mode=FAIR" 
  resources:
    requests:
      cpu: 500m
      memory: "1Gi"
    limits:
      cpu: 1
      memory: "2Gi"
  extraContainerPorts:
    - name: stream-process
      containerPort: 8181
      protocol: TCP

metrics:
  enabled: true
  masterAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/"
    prometheus.io/port: "8080"
  workerAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/"
    prometheus.io/port: "8080"
  podMonitor:
    enabled: true
    namespace: monitoring 
    interval: 10s