{
 "title": "Spark Streaming Analysis Dashboard",
 "tags": [
  "spark",
  "streaming"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alive Workers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Value{type=\"gauges\"}"
    }
   ]
  },
  {
   "title": "Running Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_apps_Value{type=\"gauges\"}"
    }
   ]
  },
  {
   "title": "Waiting Applications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_waitingApps_Value{type=\"gauges\"}"
    }
   ]
  },
  {
   "title": "Total Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_workers_Value{type=\"gauges\"}"
    }
   ]
  },
  { "title": "Streaming Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Job Events Processing Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(spark_streaming_job_events_input_rate[1m])",
     "legendFormat": "Input Rate"
    },
    {
     "expr": "rate(spark_streaming_job_events_processing_rate[1m])",
     "legendFormat": "Processing Rate"
    }
   ]
  },
  {
   "title": "Task Events Processing Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(spark_streaming_task_events_input_rate[1m])",
     "legendFormat": "Input Rate"
    },
    {
     "expr": "rate(spark_streaming_task_events_processing_rate[1m])",
     "legendFormat": "Processing Rate"
    }
   ]
  },
  { "title": "Streaming Analysis Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Tasks Count by Event Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "spark_streaming_task_count{event_type=~\".+\"}",
     "legendFormat": "Event Type {{event_type}}"
    }
   ]
  },
  {
   "title": "Tasks Count by Scheduling Class",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "spark_streaming_task_count{scheduling_class=~\".+\"}",
     "legendFormat": "{{scheduling_class}}"
    }
   ]
  },
  {
   "title": "Jobs Count by Event Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "spark_streaming_job_count{event_type=~\".+\"}",
     "legendFormat": "Event Type {{event_type}}"
    }
   ]
  },
  {
   "title": "Jobs Count by Scheduling Class",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "spark_streaming_job_count{scheduling_class=~\".+\"}",
     "legendFormat": "{{scheduling_class}}"
    }
   ]
  }
 ]
}